/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */ 

package bibliio;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Red
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private DBUtilities db = new DBUtilities();
    public MainFrame() {

        initComponents();
        db.fillTable(table);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        listButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cardPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        titreField = new javax.swing.JTextField();
        catField = new javax.swing.JTextField();
        isbnField = new javax.swing.JTextField();
        prenomField = new javax.swing.JTextField();
        nomField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        searchField = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        modifybutton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 600));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addButton.setText("Ajouter un livre");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel2.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 210, 41));

        listButton.setText("Afficher la liste des livres");
        listButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listButtonActionPerformed(evt);
            }
        });
        jPanel2.add(listButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 210, 41));

        searchButton.setText("Chercher/Modifier/Supp  un livre");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel2.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 210, 41));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel6.setSize(new Dimension(190,124));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/isima.jpg"))); // NOI18N
        jPanel5.add(jLabel6, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, 120));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 600));

        cardPanel.setLayout(new java.awt.CardLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Asap", 1, 24)); // NOI18N
        jLabel1.setText("Titre");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 160, 40));

        jLabel2.setFont(new java.awt.Font("Asap", 1, 24)); // NOI18N
        jLabel2.setText("Categorie");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 160, 40));

        jLabel3.setFont(new java.awt.Font("Asap", 1, 24)); // NOI18N
        jLabel3.setText("isbn");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 160, 40));

        jLabel4.setFont(new java.awt.Font("Asap", 1, 24)); // NOI18N
        jLabel4.setText("nom Auteur");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 160, 40));

        jLabel5.setFont(new java.awt.Font("Asap", 1, 24)); // NOI18N
        jLabel5.setText("prenom Auteur");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 160, 40));
        jPanel4.add(titreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 230, 40));

        catField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catFieldActionPerformed(evt);
            }
        });
        jPanel4.add(catField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 230, 40));

        isbnField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnFieldActionPerformed(evt);
            }
        });
        jPanel4.add(isbnField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 230, 40));

        prenomField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomFieldActionPerformed(evt);
            }
        });
        jPanel4.add(prenomField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 230, 40));

        nomField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomFieldActionPerformed(evt);
            }
        });
        jPanel4.add(nomField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 230, 40));

        jButton2.setFont(new java.awt.Font("Asap", 1, 24)); // NOI18N
        jButton2.setText("Ajouter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 180, 50));

        cardPanel.add(jPanel4, "card1");

        jPanel7.setLayout(new java.awt.BorderLayout());

        table.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Isbn", "Titre", "Nom Auteur", "Prenom Auteur", "Catégorie", "Code"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setRowHeight(25);
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(table);

        jPanel7.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        cardPanel.add(jPanel7, "card2");

        jPanel8.setLayout(new java.awt.BorderLayout());

        table1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Isbn", "Titre", "Nom Auteur", "Prenom Auteur", "Catégorie", "Code"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.setRowHeight(25);
        table1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(table1);

        jPanel8.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel8.setText("Search By :");
        jPanel6.add(jLabel8);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "isbn", "titre", "nom Auteur", "prenom Auteur", "categorie", "code" }));
        jComboBox2.setSelectedIndex(1);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBox2);

        searchField.setPreferredSize(new java.awt.Dimension(200, 30));
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        jPanel6.add(searchField);

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jPanel6.add(Search);

        modifybutton.setText("Modify");
        modifybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifybuttonActionPerformed(evt);
            }
        });
        jPanel6.add(modifybutton);

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel6.add(deleteButton);

        jPanel8.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        cardPanel.add(jPanel8, "card3");

        jPanel1.add(cardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 0, 890, 600));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void catFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catFieldActionPerformed

    private void prenomFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomFieldActionPerformed

    private void listButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, "card2");
        DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
        tableModel.setRowCount(0);
        db.fillTable(table);
    }//GEN-LAST:event_listButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, "card1");
    }//GEN-LAST:event_addButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        CardLayout cl = (CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, "card3");
        DefaultTableModel tableModel = (DefaultTableModel) table1.getModel();
        tableModel.setRowCount(0);
        db.fillTable(table1);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void isbnFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnFieldActionPerformed

    private void nomFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Book book = new Book(isbnField.getText(), titreField.getText(), catField.getText(), nomField.getText(), prenomField.getText());
        db.addBook(book);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if (table1.getSelectedRow() >=0) {
            String code = (String) table1.getValueAt(table1.getSelectedRow(), 5);
            db.deleteBook(code);
            DefaultTableModel model = (DefaultTableModel) table1.getModel();
            model.removeRow(table1.getSelectedRow());
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void modifybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifybuttonActionPerformed
        if (table1.getSelectedRow() >=0) {
            String isbn = (String) table.getValueAt(table1.getSelectedRow(), 0);
            String titre = (String) table.getValueAt(table1.getSelectedRow(), 1);
            String nomAuteur = (String) table.getValueAt(table1.getSelectedRow(), 2);
            String prenomAuteur = (String) table.getValueAt(table1.getSelectedRow(), 3);
            String categorie = (String) table.getValueAt(table1.getSelectedRow(), 4);
            String code = (String) table.getValueAt(table1.getSelectedRow(), 5);
           
          Book book = new Book(isbn, titre, categorie, nomAuteur, prenomAuteur);
            System.out.println(code);
          new ModifyBook(code,book).setVisible(true);
         
        }
        
    }//GEN-LAST:event_modifybuttonActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        int index = jComboBox2.getSelectedIndex();
        String searched = searchField.getText();
        DefaultTableModel model = (DefaultTableModel) table1.getModel();
            
        for (int i = 0; i < table1.getRowCount(); i++) {
            String string = (String) table1.getValueAt(i, index);
            if (!string.contains(searched)) {
                model.removeRow(i);
            }
        }
        if (searchField.getText().equals("")) {
            model.setRowCount(0);
            db.fillTable(table1);
        }
    }//GEN-LAST:event_SearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Search;
    private javax.swing.JButton addButton;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JTextField catField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField isbnField;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton listButton;
    private javax.swing.JButton modifybutton;
    private javax.swing.JTextField nomField;
    private javax.swing.JTextField prenomField;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    protected javax.swing.JTable table;
    protected static javax.swing.JTable table1;
    private javax.swing.JTextField titreField;
    // End of variables declaration//GEN-END:variables
}
